// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChoThueXe_UNETI02_TI17A2HN.Data;

#nullable disable

namespace QuanLyChoThueXe_UNETI02_TI17A2HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.BanGiaoXe", b =>
                {
                    b.Property<int>("MaBanGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanGiao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDatXe")
                        .HasColumnType("int");

                    b.Property<int>("MucNhienLieuBanGiao")
                        .HasColumnType("int");

                    b.Property<string>("NguoiBanGiao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoKmBanGiao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianBanGiao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangBanGiao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaBanGiao");

                    b.HasIndex("MaDatXe")
                        .IsUnique()
                        .HasDatabaseName("UX_BanGiaoXe_MaDatXe");

                    b.ToTable("BanGiaoXe", null, t =>
                        {
                            t.HasCheckConstraint("CK_BanGiaoXe_NhienLieu", "[MucNhienLieuBanGiao] >= 0 AND [MucNhienLieuBanGiao] <= 100");

                            t.HasCheckConstraint("CK_BanGiaoXe_SoKm", "[SoKmBanGiao] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.BangGiaThue", b =>
                {
                    b.Property<int>("MaBangGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangGia"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonGiaGio")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("DonGiaNgay")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<int?>("MaXe")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCocMacDinh")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaBangGia");

                    b.HasIndex("MaXe");

                    b.HasIndex("MaLoaiXe", "MaXe", "TrangThai")
                        .HasDatabaseName("IX_BangGiaThue_PhamVi_TrangThai");

                    b.ToTable("BangGiaThue", null, t =>
                        {
                            t.HasCheckConstraint("CK_BangGiaThue_DonGia", "[DonGiaNgay] > 0 AND [DonGiaGio] >= 0 AND [TienCocMacDinh] >= 0");

                            t.HasCheckConstraint("CK_BangGiaThue_KhoangHieuLuc", "[DenNgay] > [TuNgay]");

                            t.HasCheckConstraint("CK_BangGiaThue_PhamViApDung", "([MaLoaiXe] IS NOT NULL AND [MaXe] IS NULL) OR ([MaLoaiXe] IS NULL AND [MaXe] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", b =>
                {
                    b.Property<int>("MaDatXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatXe"));

                    b.Property<string>("DiaDiemNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaDiemTra")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DonGiaApDung")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ThoiGianNhanDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTraDuKien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDatXe");

                    b.HasIndex("MaKhachHang", "TrangThai")
                        .HasDatabaseName("IX_DatXe_KhachHang_TrangThai");

                    b.HasIndex("MaXe", "TrangThai", "ThoiGianNhanDuKien", "ThoiGianTraDuKien")
                        .HasDatabaseName("IX_DatXe_TrungLich");

                    b.ToTable("DatXe", null, t =>
                        {
                            t.HasCheckConstraint("CK_DatXe_ThoiGian", "[ThoiGianTraDuKien] > [ThoiGianNhanDuKien]");

                            t.HasCheckConstraint("CK_DatXe_Tien", "[DonGiaApDung] > 0 AND [TienCoc] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.HangXe", b =>
                {
                    b.Property<int>("MaHangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangXe"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHangXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaHangXe");

                    b.HasIndex("TenHangXe")
                        .IsUnique()
                        .HasDatabaseName("UX_HangXe_TenHangXe");

                    b.ToTable("HangXe", (string)null);
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHanGPLX")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoGiayPhepLaiXe")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.HasIndex("SoDienThoai")
                        .HasDatabaseName("IX_KhachHang_SoDienThoai");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.LoaiXe", b =>
                {
                    b.Property<int>("MaLoaiXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiXe"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoCho")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaLoaiXe");

                    b.HasIndex("TenLoaiXe")
                        .IsUnique()
                        .HasDatabaseName("UX_LoaiXe_TenLoaiXe");

                    b.ToTable("LoaiXe", (string)null);
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasDatabaseName("UX_TaiKhoan_TenDangNhap");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDatXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SoTienConLai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienCocDaThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienThue")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TongPhuPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDatXe");

                    b.HasIndex("NgayThanhToan", "TrangThaiThanhToan")
                        .HasDatabaseName("IX_ThanhToan_Ngay_TrangThai");

                    b.ToTable("ThanhToan", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThanhToan_Tien", "[TienThue] >= 0 AND [TongPhuPhi] >= 0 AND [TienCocDaThu] >= 0 AND [TongThanhToan] >= 0 AND [SoTienConLai] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TraXe", b =>
                {
                    b.Property<int>("MaTraXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTraXe"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDatXe")
                        .HasColumnType("int");

                    b.Property<int>("MucNhienLieuTra")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiHuHong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PhiNhienLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PhiQuaHan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PhiVuotKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SoKmTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangTra")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaTraXe");

                    b.HasIndex("MaDatXe")
                        .IsUnique()
                        .HasDatabaseName("UX_TraXe_MaDatXe");

                    b.ToTable("TraXe", null, t =>
                        {
                            t.HasCheckConstraint("CK_TraXe_NhienLieu", "[MucNhienLieuTra] >= 0 AND [MucNhienLieuTra] <= 100");

                            t.HasCheckConstraint("CK_TraXe_PhuPhi", "[PhiQuaHan] >= 0 AND [PhiVuotKm] >= 0 AND [PhiNhienLieu] >= 0 AND [PhiHuHong] >= 0");

                            t.HasCheckConstraint("CK_TraXe_SoKm", "[SoKmTra] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("AnhXe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaHangXe")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<int>("SoCho")
                        .HasColumnType("int");

                    b.Property<decimal>("SoKmHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaXe");

                    b.HasIndex("BienSo")
                        .IsUnique()
                        .HasDatabaseName("UX_Xe_BienSo");

                    b.HasIndex("MaHangXe");

                    b.HasIndex("MaLoaiXe");

                    b.ToTable("Xe", (string)null);
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.BanGiaoXe", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", "DatXe")
                        .WithOne("BanGiaoXe")
                        .HasForeignKey("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.BanGiaoXe", "MaDatXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatXe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.BangGiaThue", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.LoaiXe", "LoaiXe")
                        .WithMany("BangGiaThues")
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.Xe", "Xe")
                        .WithMany("BangGiaThues")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatXes")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.Xe", "Xe")
                        .WithMany("DatXes")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", "DatXe")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDatXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatXe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TraXe", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", "DatXe")
                        .WithOne("TraXe")
                        .HasForeignKey("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TraXe", "MaDatXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatXe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.Xe", b =>
                {
                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.HangXe", "HangXe")
                        .WithMany("Xes")
                        .HasForeignKey("MaHangXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.LoaiXe", "LoaiXe")
                        .WithMany("Xes")
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangXe");

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.DatXe", b =>
                {
                    b.Navigation("BanGiaoXe");

                    b.Navigation("ThanhToans");

                    b.Navigation("TraXe");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.HangXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DatXes");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.LoaiXe", b =>
                {
                    b.Navigation("BangGiaThues");

                    b.Navigation("Xes");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyChoThueXe_UNETI02_TI17A2HN.Models.Entities.Xe", b =>
                {
                    b.Navigation("BangGiaThues");

                    b.Navigation("DatXes");
                });
#pragma warning restore 612, 618
        }
    }
}
